-- Go Ladies — Lugares salvos da cliente (app.goladies.com.br, aba Perfil e Pedir).
--
-- A cliente guarda endereços com nome (🏠 Casa, 💼 Trabalho, 🏫 Escola...) e
-- no "Pedir viagem" toca no chip pra preencher o campo. Só ela mexe nos
-- próprios lugares; a equipe vê tudo (eh_staff) pra ajudar no CRM se precisar.
-- Depende de: schema_painel_cliente.sql (cliente_id_atual, eh_staff).
--
-- Rodar uma vez em: Supabase → SQL Editor → New query → colar tudo → Run.
-- Seguro rodar de novo se rodar por engano (idempotente).

create table if not exists public.lugares_cliente (
  id          bigint generated by default as identity primary key,
  cliente_id  bigint not null references public.clientes_transporte(id) on delete cascade,
  nome        text not null,                       -- "Casa", "Trabalho", "Escola da Lívia"
  endereco    text not null,                       -- endereço completo (como sai do Google Places)
  icone       text not null default '📍',          -- emoji escolhido no painel
  criado_em   timestamptz not null default now()
);

create index if not exists lugares_cliente_cliente_idx on public.lugares_cliente(cliente_id);

comment on table public.lugares_cliente is 'Endereços salvos pela cliente no painel (Casa, Trabalho, Escola...) pra preencher o Pedir viagem com um toque';

alter table public.lugares_cliente enable row level security;

drop policy if exists "Cliente ve os proprios lugares" on public.lugares_cliente;
create policy "Cliente ve os proprios lugares" on public.lugares_cliente
  for select using (cliente_id = public.cliente_id_atual() or public.eh_staff());

drop policy if exists "Cliente cria os proprios lugares" on public.lugares_cliente;
create policy "Cliente cria os proprios lugares" on public.lugares_cliente
  for insert with check (cliente_id = public.cliente_id_atual());

drop policy if exists "Cliente edita os proprios lugares" on public.lugares_cliente;
create policy "Cliente edita os proprios lugares" on public.lugares_cliente
  for update using (cliente_id = public.cliente_id_atual())
  with check (cliente_id = public.cliente_id_atual());

drop policy if exists "Cliente apaga os proprios lugares" on public.lugares_cliente;
create policy "Cliente apaga os proprios lugares" on public.lugares_cliente
  for delete using (cliente_id = public.cliente_id_atual());

grant select, insert, update, delete on public.lugares_cliente to authenticated;
